/* Generated By:JJTree: Do not edit this line. ASTBuiltinType.java */

package org.jzkit.a2j.codec.comp;

import java.io.FileWriter;
import java.io.StringWriter;
import java.io.Writer;

public class ASTBuiltinType extends SimpleNode {

  public int which = 0;

  public ASTBuiltinType(int id) {
    super(id);
  }

  public ASTBuiltinType(AsnParser p, int id) {
    super(p, id);
  }

  public String getTypeName()
  {
    return AsnParser.builtinTypes[which];
  }
}
