/* Generated By:JJTree: Do not edit this line. ASTCompoundValue.java */

package org.jzkit.a2j.codec.comp;

public class ASTCompoundValue extends SimpleNode {
  public ASTCompoundValue(int id) {
    super(id);
  }

  public ASTCompoundValue(AsnParser p, int id) {
    super(p, id);
  }

}
