/* Generated By:JJTree: Do not edit this line. ASTDefinedValue.java */

package org.jzkit.a2j.codec.comp;

public class ASTDefinedValue extends SimpleNode {
  public ASTDefinedValue(int id) {
    super(id);
  }

  public ASTDefinedValue(AsnParser p, int id) {
    super(p, id);
  }

}
