/* Generated By:JJTree: Do not edit this line. ASTMultipleTypeConstraints.java */

package org.jzkit.a2j.codec.comp;

public class ASTMultipleTypeConstraints extends SimpleNode {
  public ASTMultipleTypeConstraints(int id) {
    super(id);
  }

  public ASTMultipleTypeConstraints(AsnParser p, int id) {
    super(p, id);
  }

}
