/* Generated By:JJTree: Do not edit this line. ASTNamedNumberList.java */

package org.jzkit.a2j.codec.comp;

public class ASTNamedNumberList extends SimpleNode {
  public ASTNamedNumberList(int id) {
    super(id);
  }

  public ASTNamedNumberList(AsnParser p, int id) {
    super(p, id);
  }

}
