/* Generated By:JJTree: Do not edit this line. ASTValue.java */

package org.jzkit.a2j.codec.comp;

public class ASTValue extends SimpleNode {
  public ASTValue(int id) {
    super(id);
  }

  public ASTValue(AsnParser p, int id) {
    super(p, id);
  }

}
