/* Generated By:JJTree: Do not edit this line. ASTValueAssignment.java */

package org.jzkit.a2j.codec.comp;

public class ASTValueAssignment extends SimpleNode {
  public ASTValueAssignment(int id) {
    super(id);
  }

  public ASTValueAssignment(AsnParser p, int id) {
    super(p, id);
  }
}
