/* Generated By:JJTree: Do not edit this line. ASTBuiltinValue.java */

package org.jzkit.a2j.codec.comp;

public class ASTBuiltinValue extends SimpleNode {

  public int which = 0;

  public ASTBuiltinValue(int id) {
    super(id);
  }

  public ASTBuiltinValue(AsnParser p, int id) {
    super(p, id);
  }

}
