/* Generated By:JJTree: Do not edit this line. ASTBinaryString.java */

package org.jzkit.a2j.codec.comp;

public class ASTBinaryString extends SimpleNode {
  public ASTBinaryString(int id) {
    super(id);
  }

  public ASTBinaryString(AsnParser p, int id) {
    super(p, id);
  }

}
