/* Generated By:JJTree: Do not edit this line. ASTDefinedMacroName.java */

package org.jzkit.a2j.codec.comp;

public class ASTDefinedMacroName extends SimpleNode {
  public ASTDefinedMacroName(int id) {
    super(id);
  }

  public ASTDefinedMacroName(AsnParser p, int id) {
    super(p, id);
  }

}
