/* Generated By:JJTree: Do not edit this line. ASTidentifier.java */

package org.jzkit.a2j.codec.comp;

public class ASTidentifier extends SimpleNode {

  public String id = null;

  public ASTidentifier(int id) {
    super(id);
  }

  public ASTidentifier(AsnParser p, int id) {
    super(p, id);
  }

}
