/* Generated By:JJTree: Do not edit this line. ASTmodulereference.java */

package org.jzkit.a2j.codec.comp;

public class ASTmodulereference extends SimpleNode {

  public String module_ref;

  public ASTmodulereference(int id) {
    super(id);
  }

  public ASTmodulereference(AsnParser p, int id) {
    super(p, id);
  }
}
