/* Generated By:JJTree: Do not edit this line. ASTMacroReference.java */

package org.jzkit.a2j.codec.comp;

public class ASTMacroReference extends SimpleNode {
  public ASTMacroReference(int id) {
    super(id);
  }

  public ASTMacroReference(AsnParser p, int id) {
    super(p, id);
  }

}
