/* Generated By:JJTree: Do not edit this line. ASTNamedValue.java */

package org.jzkit.a2j.codec.comp;

public class ASTNamedValue extends SimpleNode {
  public ASTNamedValue(int id) {
    super(id);
  }

  public ASTNamedValue(AsnParser p, int id) {
    super(p, id);
  }

}
