/* Generated By:JJTree: Do not edit this line. ASTObjIdComponent.java */

package org.jzkit.a2j.codec.comp;

public class ASTObjIdComponent extends SimpleNode {
  public ASTObjIdComponent(int id) {
    super(id);
  }

  public ASTObjIdComponent(AsnParser p, int id) {
    super(p, id);
  }

}
