/* Generated By:JJTree: Do not edit this line. ASTSnmpObjectTypeMacroType.java */

package org.jzkit.a2j.codec.comp;

public class ASTSnmpObjectTypeMacroType extends SimpleNode {
  public ASTSnmpObjectTypeMacroType(int id) {
    super(id);
  }

  public ASTSnmpObjectTypeMacroType(AsnParser p, int id) {
    super(p, id);
  }

}
