/* Generated By:JJTree: Do not edit this line. ASTSingleTypeConstraint.java */

package org.jzkit.a2j.codec.comp;

public class ASTSingleTypeConstraint extends SimpleNode {
  public ASTSingleTypeConstraint(int id) {
    super(id);
  }

  public ASTSingleTypeConstraint(AsnParser p, int id) {
    super(p, id);
  }

}
