/* Generated By:JJTree: Do not edit this line. ASTSymbolsExported.java */

package org.jzkit.a2j.codec.comp;

public class ASTSymbolsExported extends SimpleNode {
  public ASTSymbolsExported(int id) {
    super(id);
  }

  public ASTSymbolsExported(AsnParser p, int id) {
    super(p, id);
  }

}
