/* Generated By:JJTree: Do not edit this line. ASTValueConstraint.java */

package org.jzkit.a2j.codec.comp;

public class ASTValueConstraint extends SimpleNode {
  public ASTValueConstraint(int id) {
    super(id);
  }

  public ASTValueConstraint(AsnParser p, int id) {
    super(p, id);
  }

}
