/* Generated By:JJTree: Do not edit this line. ASTAssignedIdentifier.java */

package org.jzkit.a2j.codec.comp;

public class ASTAssignedIdentifier extends SimpleNode {
  public ASTAssignedIdentifier(int id) {
    super(id);
  }

  public ASTAssignedIdentifier(AsnParser p, int id) {
    super(p, id);
  }

}
