/* Generated By:JJTree: Do not edit this line. ASTBooleanValue.java */

package org.jzkit.a2j.codec.comp;

public class ASTBooleanValue extends SimpleNode {

  public Boolean value = null;

  public ASTBooleanValue(int id) {
    super(id);
  }

  public ASTBooleanValue(AsnParser p, int id) {
    super(p, id);
  }

}
