/* Generated By:JJTree: Do not edit this line. ASTConstraint.java */

package org.jzkit.a2j.codec.comp;

public class ASTConstraint extends SimpleNode {
  public ASTConstraint(int id) {
    super(id);
  }

  public ASTConstraint(AsnParser p, int id) {
    super(p, id);
  }

}
