/* Generated By:JJTree: Do not edit this line. ASTComponentsType.java */

package org.jzkit.a2j.codec.comp;

public class ASTComponentsType extends SimpleNode {
  public ASTComponentsType(int id) {
    super(id);
  }

  public ASTComponentsType(AsnParser p, int id) {
    super(p, id);
  }

}
