/* Generated By:JJTree: Do not edit this line. ASTInnerTypeConstraints.java */

package org.jzkit.a2j.codec.comp;

public class ASTInnerTypeConstraints extends SimpleNode {
  public ASTInnerTypeConstraints(int id) {
    super(id);
  }

  public ASTInnerTypeConstraints(AsnParser p, int id) {
    super(p, id);
  }

}
