/* Generated By:JJTree: Do not edit this line. ASTMacroDefinition.java */

package org.jzkit.a2j.codec.comp;

public class ASTMacroDefinition extends SimpleNode {
  public ASTMacroDefinition(int id) {
    super(id);
  }

  public ASTMacroDefinition(AsnParser p, int id) {
    super(p, id);
  }
}
