/* Generated By:JJTree: Do not edit this line. ASTSnmpDefValPart.java */

package org.jzkit.a2j.codec.comp;

public class ASTSnmpDefValPart extends SimpleNode {
  public ASTSnmpDefValPart(int id) {
    super(id);
  }

  public ASTSnmpDefValPart(AsnParser p, int id) {
    super(p, id);
  }

}
