/* Generated By:JJTree: Do not edit this line. ASTTypeConstraints.java */

package org.jzkit.a2j.codec.comp;

public class ASTTypeConstraints extends SimpleNode {
  public ASTTypeConstraints(int id) {
    super(id);
  }

  public ASTTypeConstraints(AsnParser p, int id) {
    super(p, id);
  }

}
