/* Generated By:JJTree: Do not edit this line. ASTTextualConventionMacroType.java */

package org.jzkit.a2j.codec.comp;

public class ASTTextualConventionMacroType extends SimpleNode {
  public ASTTextualConventionMacroType(int id) {
    super(id);
  }

  public ASTTextualConventionMacroType(AsnParser p, int id) {
    super(p, id);
  }

}
