/* Generated By:JJTree: Do not edit this line. ASTHexString.java */

package org.jzkit.a2j.codec.comp;

public class ASTHexString extends SimpleNode {
  public ASTHexString(int id) {
    super(id);
  }

  public ASTHexString(AsnParser p, int id) {
    super(p, id);
  }

}
