/* Generated By:JJTree: Do not edit this line. ASTObjectIdentifierValue.java */

package org.jzkit.a2j.codec.comp;

public class ASTObjectIdentifierValue extends SimpleNode {
  public ASTObjectIdentifierValue(int id) {
    super(id);
  }

  public ASTObjectIdentifierValue(AsnParser p, int id) {
    super(p, id);
  }

}
