/* Generated By:JJTree: Do not edit this line. ASTSnmpIndexPart.java */

package org.jzkit.a2j.codec.comp;

public class ASTSnmpIndexPart extends SimpleNode {
  public ASTSnmpIndexPart(int id) {
    super(id);
  }

  public ASTSnmpIndexPart(AsnParser p, int id) {
    super(p, id);
  }

}
