/* Generated By:JJTree: Do not edit this line. ASTTypeOrValueList.java */

package org.jzkit.a2j.codec.comp;

public class ASTTypeOrValueList extends SimpleNode {
  public ASTTypeOrValueList(int id) {
    super(id);
  }

  public ASTTypeOrValueList(AsnParser p, int id) {
    super(p, id);
  }

}
