/* Generated By:JJTree: Do not edit this line. ASTtypereference.java */

package org.jzkit.a2j.codec.comp;

public class ASTtypereference extends SimpleNode {

  public String typeref = null;

  public ASTtypereference(int id) {
    super(id);
  }

  public ASTtypereference(AsnParser p, int id) {
    super(p, id);
  }

}
